Monday:
  Clay: 6:15PM
  Semmie: 6:15PM
Tuesday:
  Clay: 6:15PM
  Semmie: 6:15PM
Wednesday:
  Clay: 6:15PM
  Semmie: 7:45AM
Thursday:
  Semmie: 7:45AM
  Clay: 6:15PM
Friday:
  Clay: 2:45PM
  Semmie: 7:45AM