Monday:
  Clay: 6:15PM
  Semmie: 6:15PM
Tuesday:
  Clay: 6:15PM
  Semmie: 6:15PM
Wednesday:
  Clay: 6:15PM
  Semmie: 7:45AM
Thursday:
  Clay: 7:00PM pool
  Semmie: 7:45AM
Friday:
  Clay: 2:45PM
  Semmie: 7:45AM